; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:esp-wrover-kit]
platform = espressif32
board = esp-wrover-kit
framework = arduino
monitor_speed = 115200

; Flag indispensable pour activer la RAM externe (PSRAM) du module WROVER
build_flags = 
    -DBOARD_HAS_PSRAM
    -I lib/hubDataStorage
    -I .pio/libdeps/esp-wrover-kit/ArduinoJson/src
    -I .pio/libdeps/esp-wrover-kit/ArduinoEigen


lib_extra_dirs =
    ..
    ../..
    ../../..

lib_ignore =
    Essais_carte_MaUWB

lib_deps =
    hideakitai/ArduinoEigen
    bblanchon/ArduinoJson
    hubDataStorage
    MessageManager

; A retirer si on veut tester la librairie MessageManager
extra_scripts =
    pre:ignore_files.py