[env:esp-wrover-kit]
platform = espressif32
board = esp-wrover-kit
framework = arduino
monitor_speed = 115200

lib_ldf_mode = deep+

; 1. On pointe uniquement vers le dossier partagé
lib_extra_dirs =
    ../../Librairie_PlatformIO/lib

; 2. On liste explicitement TOUTES les librairies nécessaires
lib_deps =
    hideakitai/ArduinoEigen
    bblanchon/ArduinoJson
    adafruit/Adafruit GFX Library @ ^1.11.9
    adafruit/Adafruit SSD1306 @ ^2.5.9
    adafruit/Adafruit BusIO @ ^1.16.1
    SPI
    Wire
    
    ; --- Tes librairies partagées ---
    MessageManager
    UWBDataManager

build_flags = 
    -DBOARD_HAS_PSRAM

; /!\ ON SUPPRIME TOTALEMENT LES LIGNES "build_src_filter" ET "-I" /!\

lib_ignore =
    Essais_carte_MaUWB

extra_scripts =
    pre:ignore_files.py