[env:esp-wrover-kit]
platform = espressif32
board = nodemcu-32s
framework = arduino
monitor_speed = 115200

lib_ldf_mode = deep+

; 1. On pointe vers les dossiers qui CONTIENNENT tes librairies
lib_extra_dirs =
    ../../Librairie_PlatformIO/lib
    ../..  ; <-- Permet de trouver Algorithme-trilateration
    ..     ; <-- Permet de trouver librairie_hub

lib_deps =
    ; --- Librairies externes (Internet) ---
    hideakitai/ArduinoEigen
    bblanchon/ArduinoJson
    adafruit/Adafruit GFX Library @ ^1.11.9
    adafruit/Adafruit SSD1306 @ ^2.5.9
    adafruit/Adafruit BusIO @ ^1.16.1
    SPI
    Wire
    
    ; --- Tes librairies partagées et mathématiques (Trouvées grâce aux lib_extra_dirs) ---
    MessageManager
    UWBDataManager
    Algorithme-trilateration
    librairie_hub
    
    ; (On a supprimé la liste des librairies locales ici, PlatformIO les trouvera tout seul dans le dossier lib/)

build_flags = 
    -DBOARD_HAS_PSRAM
    -I include    ; Autorise les librairies à lire le dossier include/
    -I src        ; Autorise les librairies à lire le dossier src/

; 2. LA MAGIE EST ICI : On empêche le scanner de confondre tes projets avec des librairies !
lib_ignore =
    Essais_carte_MaUWB
    Algorithme_final_hub
    firmware-esp32-wrover

extra_scripts =
    pre:ignore_files.py