name=Messages
version=1.0.0
author=Maxime_LE_BLAN
maintainer=Maxime_LE_BLAN
sentence=Gestion des messages pour le Hub et les Ancres UWB.
paragraph=Cette librairie partagée permet de centraliser les structures de données ESP-NOW.
category=Communication
url=
architectures=esp32