[env:esp32-s3-devkitc-1]
platform = espressif32
board = esp32-s3-devkitc-1
framework = arduino
monitor_speed = 115200

board_build.arduino.memory_type = qio_opi
board_build.flash_mode = qio
board_build.psram_type = opi
board_upload.flash_size = 16MB
board_upload.maximum_size = 16777216

lib_ldf_mode = deep

build_flags = 
	-DBOARD_HAS_PSRAM
	-D ARDUINO_USB_MODE=1
	-D ARDUINO_USB_CDC_ON_BOOT=1
	-D LV_CONF_SKIP=1
	-D LV_COLOR_DEPTH=16
	-D LV_FONT_MONTSERRAT_14=1
	-D LV_FONT_MONTSERRAT_10=1

lib_deps = 
	lvgl/lvgl@^8.4.0
	moononournation/GFX Library for Arduino @ 1.2.8
	https://github.com/TAMCTec/gt911-arduino.git
	bblanchon/ArduinoJson
	mathieucarbou/AsyncTCP
	mathieucarbou/ESPAsyncWebServer