; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

; PlatformIO Project Configuration File

[env:xiaoble]
platform = https://github.com/maxgerhardt/platform-nordicnrf52.git
board = xiaoble_adafruit
framework = arduino
monitor_speed = 115200

# Analyse en profondeur des dépendances 
lib_ldf_mode = deep+
lib_archive = no

# Indique le dossier partagé contenant les bibliothèques locales
lib_extra_dirs =
    ../Librairie_PlatformIO/lib/

# 1. On SUPPRIME le blocage par défaut des exceptions imposé par la carte
build_unflags = -fno-exceptions

# 2. On FORCE l'activation des exceptions pour tout le projet et les libs externes
build_flags = -fexceptions

# Dépendances requises
lib_deps =
    Wire
    SPI
    adafruit/Adafruit BMP5xx Library
    adafruit/Adafruit SSD1306 @ ^2.5.17
    adafruit/Adafruit GFX Library @ ^1.12.6
    adafruit/Adafruit BusIO @ ^1.17.4