; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

; PlatformIO Project Configuration File

[env:xiaoble]
platform = https://github.com/maxgerhardt/platform-nordicnrf52
board = xiaoble
framework = arduino
monitor_speed = 115200

# 1. Force l'analyse en profondeur des dépendances imbriquées
lib_ldf_mode = deep+
lib_archive = no

# 2. Indique le dossier partagé contenant les bibliothèques
lib_extra_dirs =
    ../Librairie_PlatformIO/lib/

# 3. Règle le problème de try/catch (UWBDataManager)
# et indique à la XIAO d'ignorer le fichier CANMessageManager réservé à l'ESP32
build_flags = 
    -fexceptions
    -DSRC_FILTER="-<../Librairie_PlatformIO/lib/MessageManager/CANMessageManager.cpp>"

# 4. Garde la compilation par défaut pour le dossier src de la XIAO
build_src_filter =
    +<*>

# 5. Dépendances requises
lib_deps =
    Wire
    SPI
    adafruit/Adafruit BMP5xx Library
    adafruit/Adafruit SSD1306 @ ^2.5.17
    adafruit/Adafruit GFX Library @ ^1.12.6
    adafruit/Adafruit BusIO @ ^1.17.4